// Code generated by "stringer -linecomment -type OnConflict,Ordering,ForeignKeyAction,ForeignKeyDeferrable,ConstraintType -output enums_string.go"; DO NOT EDIT.

package x

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ConflictNone-0]
	_ = x[ConflictRollback-1]
	_ = x[ConflictAbort-2]
	_ = x[ConflictFail-3]
	_ = x[ConflictIgnore-4]
	_ = x[ConflictReplace-5]
}

const _OnConflict_name = "NOTHINGROLLBACKABORTFAILIGNOREREPLACE"

var _OnConflict_index = [...]uint8{0, 7, 15, 20, 24, 30, 37}

func (i OnConflict) String() string {
	if i >= OnConflict(len(_OnConflict_index)-1) {
		return "OnConflict(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OnConflict_name[_OnConflict_index[i]:_OnConflict_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OrderingNone-0]
	_ = x[OrderingAsc-1]
	_ = x[OrderingDesc-2]
}

const _Ordering_name = "ORDER_NONEORDER_ASCORDER_DESC"

var _Ordering_index = [...]uint8{0, 10, 19, 29}

func (i Ordering) String() string {
	if i >= Ordering(len(_Ordering_index)-1) {
		return "Ordering(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Ordering_name[_Ordering_index[i]:_Ordering_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ForeignKeyActionNone-0]
	_ = x[ForeignKeyActionSetNull-1]
	_ = x[ForeignKeyActionSetDefault-2]
	_ = x[ForeignKeyActionCascade-3]
	_ = x[ForeignKeyActionRestrict-4]
	_ = x[ForeignKeyActionNoAction-5]
}

const _ForeignKeyAction_name = "SET_NONESET_NULLSET_DEFAULTCASCADERESTRICTNO_ACTION"

var _ForeignKeyAction_index = [...]uint8{0, 8, 16, 27, 34, 42, 51}

func (i ForeignKeyAction) String() string {
	if i >= ForeignKeyAction(len(_ForeignKeyAction_index)-1) {
		return "ForeignKeyAction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ForeignKeyAction_name[_ForeignKeyAction_index[i]:_ForeignKeyAction_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ForeignKeyDeferrableNone-0]
	_ = x[ForeignKeyDeferrableDeferrable-1]
	_ = x[ForeignKeyDeferrableInitiallyDeferred-2]
	_ = x[ForeignKeyDeferrableInitiallyImmediate-3]
	_ = x[ForeignKeyDeferrableNotDeferrable-4]
	_ = x[ForeignKeyDeferrableNotDeferrableInitiallyDeferred-5]
	_ = x[ForeignKeyDeferrableNotDeferrableInitiallyImmediate-6]
}

const _ForeignKeyDeferrable_name = "NONEDEFERRABLEDEFERRABLE_INITIALLY_DEFERREDDEFERRABLE_INITIALLY_IMMEDIATENOT_DEFERRABLENOT_DEFERRABLE_INITIALLY_DEFERREDNOT_DEFERRABLE_INITIALLY_IMMEDIATE"

var _ForeignKeyDeferrable_index = [...]uint8{0, 4, 14, 43, 73, 87, 120, 154}

func (i ForeignKeyDeferrable) String() string {
	if i >= ForeignKeyDeferrable(len(_ForeignKeyDeferrable_index)-1) {
		return "ForeignKeyDeferrable(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ForeignKeyDeferrable_name[_ForeignKeyDeferrable_index[i]:_ForeignKeyDeferrable_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ConstraintPrimaryKey-0]
	_ = x[ConstraintUnique-1]
	_ = x[ConstraintCheck-2]
	_ = x[ConstraintForeignKey-3]
}

const _ConstraintType_name = "PRIMARY_KEYUNIQUECHECKFOREIGN_KEY"

var _ConstraintType_index = [...]uint8{0, 11, 17, 22, 33}

func (i ConstraintType) String() string {
	if i >= ConstraintType(len(_ConstraintType_index)-1) {
		return "ConstraintType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ConstraintType_name[_ConstraintType_index[i]:_ConstraintType_index[i+1]]
}
